use std::fs;

fn repo_root() -> &'static str {
    env!("CARGO_MANIFEST_DIR")
}

#[test]
fn cargo_toml_contains_dist_metadata() {
    let cargo_toml =
        fs::read_to_string(format!("{}/Cargo.toml", repo_root())).expect("should read Cargo.toml");

    assert!(cargo_toml.contains("repository = \"https://github.com/Dragonchu/resumeclaw\""));
    assert!(cargo_toml.contains("license = \"MIT\""));
    assert!(cargo_toml.contains("[profile.dist]"));
}

#[test]
fn cargo_dist_release_files_are_present() {
    let dist_workspace = fs::read_to_string(format!("{}/dist-workspace.toml", repo_root()))
        .expect("should read dist-workspace.toml");
    assert!(dist_workspace.contains("cargo-dist-version = \"0.31.0\""));
    assert!(dist_workspace.contains("ci = \"github\""));
    assert!(dist_workspace.contains("hosting = \"github\""));

    let workflow =
        fs::read_to_string(format!("{}/.github/workflows/release.yml", repo_root()))
            .expect("should read cargo-dist release workflow");
    assert!(workflow.contains("autogenerated by dist"));
    assert!(workflow.contains("name: Release"));
    assert!(workflow.contains("dist build"));
}
